name: "Telegram Bot"
version: "0.0.4"
slug: "telegram_bot"
description: "Бот для управления домом через Telegram"
hassio_api: true
homeassistant_api: true

arch:
  - aarch64
  - amd64
image: "ghcr.io/anykei/telegram_ha_bot"

init: false

map:
  - config:rw
options:
  bot_token: ""
  root_user: ""
schema:
  bot_token: str
  root_user: str
